In [57]:
# Loading of otrain data. Copied from Open Train notebook

# library for loading data and tables
# we will use it a lot, so we use its standard abbreviation - pd
import pandas as pd
import numpy as np

# plotting library
# loading it changes default styles to much nicer ones
import seaborn as sns

# IPython Notebook option to show plots in the notebook (not in a separate window)
%matplotlib inline

In [58]:
df = pd.read_excel("data/otrain/2015_04_05_06.xlsx")

In [59]:
df['Planned_Stop'].fillna(0, inplace=True)
df['Actual_Stop'].fillna(0, inplace=True)
di = {'מתוכננת': True, 'לא מתוכננת': False}
df.replace({"Planned": di}, inplace=True)
df = df.rename(columns={'Station_typ': "Station_type", "Planned_Depratur": "Planned_Deprature"})
df = df[(df["Station_type"] != 'מוצא תפעולי') & (df["Station_type"] != "יעד תפעולי")]
df.ix[df["Station_type"] == "יעד מסחרי", "Actual_Departure"] = pd.NaT
df.ix[df["Station_type"] == "מוצא מסחרי", "Actual_Arrival"] = pd.NaT

In [62]:
df_full = df
df = df_full[df_full.Train_Date == '2015-04-01']

In [63]:
df.count()

Train_Date             6971
Train_Number           6971
Planned                6971
Station_number         6971
Station_Description    6971
Station_Order          6971
Route_Description      6971
Station_type           6971
Planned_Stop           6971
Actual_Stop            6971
Planned_Deprature      6553
Actual_Departure       6514
Planned_Arrival        6556
Actual_Arrival         6515
dtype: int64

In [69]:
gtfs = pd.read_csv('data/gtfs/merged/stops_20150401.txt')

In [70]:
gtfs.count()

trip_id            5586
date               5586
route_id           5586
route_long_name    5586
trip_headsign      5586
stop_id            5586
stop_name          5586
arrival_time       5586
departure_time     5586
stop_sequence      5586
gtfs_date          5586
dtype: int64

In [41]:
# add route id field to make things easier 
routes_heb = ['נהריה - נתבג', 
             'נהריה - באר שבע מרכז',
             'נהריה - מודיעין מרכז',
             'בנימינה - אשקלון',
             'נהריה - חוף הכרמל',
             'הרצליה- ירושלים מלחה',
             'הוד השרון-שדרות',
             'חיפה מרכז - בש מרכז',
             'באר שבע צפון-דימונה',
             'נתניה-הראשונים',
             'קו לא מוגדר', 
             np.nan]

routes_eng = ['Nahariyya - Ben Gurion Airport',
              "Nahariyya - Be'er Sheva Center",
              'Nahariyya - Modiin Center',
              'Binyamina - Ashkelon',
             "Nahariyya - Haifa Hof HaKar     mel (Razi'el)",
             'Hertsliya - Jerusalem Malha',
             'Hod HaSharon - Sderot',
             "Haifa Center-Be'er Sheva Center",
             "Be'er Sheva North University - Dimona",
             'Netanya - Rishon LeTsiyyon HaRishonim',
             'undefined route',
             np.nan]

heb_to_eng = {x: y for x,y in zip(routes_heb, routes_eng)}

from csv import DictReader
from io import TextIOWrapper
f = open('data/gtfs/routes.txt', encoding='utf-8-sig')
name_to_id = {row['route_long_name']: row['route_id'] for row in  DictReader(f)}
name_to_id[np.nan] = np.nan
name_to_id['undefined route'] = '0'
heb_to_id = {x: name_to_id[heb_to_eng[x]] for x in routes_heb}
df['Route_Id'] = df['Route_Description'].map(heb_to_id)
df.head()

,Train_Date,Train_Number,Planned,Station_number,Station_Description,Station_Order,Route_Description,Station_type,Planned_Stop,Actual_Stop,Planned_Deprature,Actual_Departure,Planned_Arrival,Actual_Arrival,Route_Id
0,2015-04-01,1,True,1600,נהריה,1,נהריה - נתבג,מוצא,1,1,2015-04-01 23:13:00,2015-04-01 23:13:52,NaT,NaT,60
1,2015-04-01,1,True,1500,עכו,2,נהריה - נתבג,ביניים,1,1,2015-04-01 23:23:00,2015-04-01 23:23:11,2015-04-01 23:21:00,2015-04-01 23:21:04,60
2,2015-04-01,1,True,800,קרית מוצקין,5,נהריה - נתבג,ביניים,1,1,2015-04-01 23:33:00,2015-04-01 23:32:08,2015-04-01 23:32:00,2015-04-01 23:31:19,60
3,2015-04-01,1,True,700,קרית חיים,6,נהריה - נתבג,ביניים,0,0,2015-04-01 23:36:00,2015-04-01 23:34:38,2015-04-01 23:36:00,2015-04-01 23:34:38,60
4,2015-04-01,1,True,1300,חוצות מפרץ,7,נהריה - נתבג,ביניים,0,0,2015-04-01 23:37:00,2015-04-01 23:35:31,2015-04-01 23:37:00,2015-04-01 23:35:31,60

In [71]:
df[df.Planned_Stop==1].count()

Train_Date             5565
Train_Number           5565
Planned                5565
Station_number         5565
Station_Description    5565
Station_Order          5565
Route_Description      5565
Station_type           5565
Planned_Stop           5565
Actual_Stop            5565
Planned_Deprature      5147
Actual_Departure       5108
Planned_Arrival        5150
Actual_Arrival         5109
dtype: int64

In [78]:
df[df.Station_number==1600]

,Train_Date,Train_Number,Planned,Station_number,Station_Description,Station_Order,Route_Description,Station_type,Planned_Stop,Actual_Stop,Planned_Deprature,Actual_Departure,Planned_Arrival,Actual_Arrival
0,2015-04-01,1,True,1600,נהריה,1,נהריה - נתבג,מוצא,1,1,2015-04-01 23:13:00,2015-04-01 23:13:52,NaT,NaT
42,2015-04-01,2,True,1600,נהריה,37,נהריה - נתבג,יעד,1,1,NaT,NaT,2015-04-01 02:46:00,2015-04-01 02:45:45
43,2015-04-01,3,True,1600,נהריה,1,נהריה - נתבג,מוצא,1,1,2015-04-01 00:13:00,2015-04-01 00:13:47,NaT,NaT
84,2015-04-01,4,True,1600,נהריה,34,נהריה - נתבג,יעד,1,1,NaT,NaT,2015-04-01 03:46:00,2015-04-01 03:47:37
85,2015-04-01,5,True,1600,נהריה,1,נהריה - נתבג,מוצא,1,1,2015-04-01 01:13:00,2015-04-01 01:13:40,NaT,NaT
126,2015-04-01,6,True,1600,נהריה,34,נהריה - נתבג,יעד,1,1,NaT,NaT,2015-04-01 04:46:00,2015-04-01 04:44:45
127,2015-04-01,7,True,1600,נהריה,1,נהריה - נתבג,מוצא,1,1,2015-04-01 02:13:00,2015-04-01 02:13:29,NaT,NaT
168,2015-04-01,8,True,1600,נהריה,34,נהריה - נתבג,יעד,1,1,NaT,NaT,2015-04-01 05:48:00,2015-04-01 05:53:17
169,2015-04-01,9,True,1600,נהריה,1,נהריה - נתבג,מוצא,1,1,2015-04-01 03:13:00,2015-04-01 03:13:18,NaT,NaT
210,2015-04-01,10,True,1600,נהריה,34,נהריה - נתבג,יעד,1,1,NaT,NaT,2015-04-01 06:58:00,2015-04-01 06:59:05
211,2015-04-01,11,True,1600,נהריה,1,נהריה - נתבג,מוצא,1,1,2015-04-01 03:57:00,2015-04-01 03:58:52,NaT,NaT
271,2015-04-01,20,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 07:59:00,2015-04-01 07:58:33
272,2015-04-01,21,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 05:29:00,2015-04-01 05:29:42,NaT,NaT
327,2015-04-01,22,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 08:59:00,2015-04-01 08:58:35
328,2015-04-01,23,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 06:29:00,2015-04-01 06:30:35,NaT,NaT
383,2015-04-01,24,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 09:59:00,2015-04-01 09:58:01
384,2015-04-01,25,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 07:29:00,2015-04-01 07:29:37,NaT,NaT
439,2015-04-01,26,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 10:59:00,2015-04-01 10:58:11
440,2015-04-01,27,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 08:29:00,2015-04-01 08:29:53,NaT,NaT
479,2015-04-01,29,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 09:29:00,2015-04-01 09:29:41,NaT,NaT
600,2015-04-01,36,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 15:59:00,2015-04-01 15:58:37
639,2015-04-01,38,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 16:59:00,2015-04-01 17:06:45
640,2015-04-01,39,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 14:29:00,2015-04-01 14:29:21,NaT,NaT
695,2015-04-01,40,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 17:59:00,2015-04-01 17:58:25
696,2015-04-01,41,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 15:29:00,2015-04-01 15:31:14,NaT,NaT
751,2015-04-01,42,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 18:59:00,2015-04-01 18:58:50
752,2015-04-01,43,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 16:29:00,2015-04-01 16:29:50,NaT,NaT
807,2015-04-01,44,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 19:59:00,2015-04-01 19:59:07
808,2015-04-01,45,True,1600,נהריה,1,נהריה - באר שבע מרכז,מוצא,1,1,2015-04-01 17:29:00,2015-04-01 17:29:27,NaT,NaT
863,2015-04-01,46,True,1600,נהריה,46,נהריה - באר שבע מרכז,יעד,1,1,NaT,NaT,2015-04-01 20:59:00,2015-04-01 21:03:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3377,2015-04-01,408,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 07:18:00,2015-04-01 07:16:39
3378,2015-04-01,409,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 06:12:00,2015-04-01 06:13:04,NaT,NaT
3412,2015-04-01,414,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 08:18:00,2015-04-01 08:17:40
3413,2015-04-01,415,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 07:12:00,2015-04-01 07:12:23,NaT,NaT
3446,2015-04-01,420,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 09:18:00,2015-04-01 09:17:16
3447,2015-04-01,421,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 08:12:00,2015-04-01 08:12:23,NaT,NaT
3480,2015-04-01,426,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 10:18:00,2015-04-01 10:16:17
3481,2015-04-01,427,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 09:12:00,2015-04-01 09:13:26,NaT,NaT
3514,2015-04-01,432,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 11:18:00,2015-04-01 11:18:34
3515,2015-04-01,433,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 10:12:00,2015-04-01 10:12:54,NaT,NaT
3546,2015-04-01,438,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 12:18:00,2015-04-01 12:19:46
3547,2015-04-01,439,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 11:12:00,2015-04-01 11:12:22,NaT,NaT
3580,2015-04-01,444,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 13:18:00,2015-04-01 13:17:04
3581,2015-04-01,445,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 12:12:00,2015-04-01 12:13:10,NaT,NaT
3614,2015-04-01,450,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 14:18:00,2015-04-01 14:16:55
3615,2015-04-01,451,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 13:12:00,2015-04-01 13:12:56,NaT,NaT
3648,2015-04-01,456,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 15:18:00,2015-04-01 15:21:04
3649,2015-04-01,457,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 14:12:00,2015-04-01 14:12:24,NaT,NaT
3682,2015-04-01,462,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 16:18:00,2015-04-01 16:16:51
3683,2015-04-01,463,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 15:12:00,2015-04-01 15:12:32,NaT,NaT
3716,2015-04-01,468,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 17:18:00,2015-04-01 17:23:12
3717,2015-04-01,469,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 16:12:00,2015-04-01 16:13:10,NaT,NaT
3750,2015-04-01,474,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 18:18:00,2015-04-01 18:17:58
3751,2015-04-01,475,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 17:12:00,2015-04-01 17:12:29,NaT,NaT
3784,2015-04-01,480,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 19:18:00,2015-04-01 19:19:25
3785,2015-04-01,481,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 18:12:00,2015-04-01 18:12:32,NaT,NaT
3818,2015-04-01,486,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 20:18:00,2015-04-01 20:17:17
3819,2015-04-01,487,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 19:12:00,2015-04-01 19:13:39,NaT,NaT
3852,2015-04-01,492,True,1600,נהריה,13,נהריה - חוף הכרמל,יעד,1,1,NaT,NaT,2015-04-01 21:18:00,2015-04-01 21:20:50
3853,2015-04-01,493,True,1600,נהריה,1,נהריה - חוף הכרמל,מוצא,1,1,2015-04-01 20:12:00,2015-04-01 20:12:30,NaT,NaT

In [79]:
gtfs[gtfs.stop_id==1600]

,trip_id,date,route_id,route_long_name,trip_headsign,stop_id,stop_name,arrival_time,departure_time,stop_sequence,gtfs_date
49,010415_00001,20150401,60,Nahariyya - Ben Gurion Airport,Ben Gurion Airport,1600,Nahariyya,23:13:00,23:13:00,1,20150331
73,010415_00010,20150401,60,Nahariyya - Ben Gurion Airport,Nahariyya,1600,Nahariyya,06:58:00,06:58:00,14,20150331
88,010415_00100,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,07:33:00,07:33:00,15,20150331
89,010415_00101,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,04:52:00,04:52:00,1,20150331
119,010415_00102,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,08:33:00,08:33:00,15,20150331
120,010415_00103,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,05:54:00,05:54:00,1,20150331
149,010415_00104,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,09:33:00,09:33:00,15,20150331
150,010415_00105,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,06:54:00,06:54:00,1,20150331
179,010415_00106,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,10:33:00,10:33:00,15,20150331
180,010415_00107,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,07:54:00,07:54:00,1,20150331
209,010415_00108,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,11:33:00,11:33:00,15,20150331
210,010415_00109,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,08:54:00,08:54:00,1,20150331
225,010415_00011,20150401,60,Nahariyya - Ben Gurion Airport,Ben Gurion Airport,1600,Nahariyya,03:57:00,03:57:00,1,20150331
253,010415_00110,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,12:33:00,12:33:00,15,20150331
254,010415_00111,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,09:54:00,09:54:00,1,20150331
283,010415_00112,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,13:33:00,13:33:00,15,20150331
284,010415_00113,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,10:54:00,10:54:00,1,20150331
313,010415_00114,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,14:33:00,14:33:00,15,20150331
314,010415_00115,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,11:54:00,11:54:00,1,20150331
343,010415_00116,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,15:33:00,15:33:00,15,20150331
344,010415_00117,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,12:54:00,12:54:00,1,20150331
373,010415_00118,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,16:33:00,16:33:00,15,20150331
374,010415_00119,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,13:54:00,13:54:00,1,20150331
403,010415_00120,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,17:33:00,17:33:00,15,20150331
404,010415_00121,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,14:54:00,14:54:00,1,20150331
433,010415_00122,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,18:33:00,18:33:00,15,20150331
434,010415_00123,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,15:54:00,15:54:00,1,20150331
463,010415_00124,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,19:33:00,19:33:00,15,20150331
464,010415_00125,20150401,51,Nahariyya - Modiin Center,Modiin Center,1600,Nahariyya,16:54:00,16:54:00,1,20150331
493,010415_00126,20150401,51,Nahariyya - Modiin Center,Nahariyya,1600,Nahariyya,20:33:00,20:33:00,15,20150331
...,...,...,...,...,...,...,...,...,...,...,...
2465,010415_00439,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,11:12:00,11:12:00,1,20150331
2491,010415_00044,20150401,52,Nahariyya - Be'er Sheva Center,Nahariyya,1600,Nahariyya,19:59:00,19:59:00,18,20150331
2516,010415_00444,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,13:18:00,13:18:00,9,20150331
2517,010415_00445,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,12:12:00,12:12:00,1,20150331
2542,010415_00045,20150401,52,Nahariyya - Be'er Sheva Center,Be'er Sheva Center,1600,Nahariyya,17:29:00,17:29:00,1,20150331
2568,010415_00450,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,14:18:00,14:18:00,9,20150331
2569,010415_00451,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,13:12:00,13:12:00,1,20150331
2602,010415_00456,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,15:18:00,15:18:00,9,20150331
2603,010415_00457,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,14:12:00,14:12:00,1,20150331
2637,010415_00046,20150401,52,Nahariyya - Be'er Sheva Center,Nahariyya,1600,Nahariyya,20:59:00,20:59:00,18,20150331
2654,010415_00462,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,16:18:00,16:18:00,9,20150331
2655,010415_00463,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,15:12:00,15:12:00,1,20150331
2688,010415_00468,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,17:18:00,17:18:00,9,20150331
2689,010415_00469,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,16:12:00,16:12:00,1,20150331
2698,010415_00047,20150401,52,Nahariyya - Be'er Sheva Center,Be'er Sheva Center,1600,Nahariyya,18:29:00,18:29:00,1,20150331
2740,010415_00474,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,18:18:00,18:18:00,9,20150331
2741,010415_00475,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,17:12:00,17:12:00,1,20150331
2783,010415_00048,20150401,52,Nahariyya - Be'er Sheva Center,Nahariyya,1600,Nahariyya,21:59:00,21:59:00,18,20150331
2792,010415_00480,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,19:18:00,19:18:00,9,20150331
2793,010415_00481,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,18:12:00,18:12:00,1,20150331
2826,010415_00486,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,20:18:00,20:18:00,9,20150331
2827,010415_00487,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,19:12:00,19:12:00,1,20150331
2844,010415_00049,20150401,52,Nahariyya - Be'er Sheva Center,Be'er Sheva Center,1600,Nahariyya,19:29:00,19:29:00,1,20150331
2878,010415_00492,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Nahariyya,1600,Nahariyya,21:18:00,21:18:00,9,20150331
2879,010415_00493,20150401,53,Nahariyya - Haifa Hof HaKar mel (Razi'el),Haifa Hof HaKarmel (Razi'el),1600,Nahariyya,20:12:00,20:12:00,1,20150331
2904,010415_00005,20150401,60,Nahariyya - Ben Gurion Airport,Ben Gurion Airport,1600,Nahariyya,01:13:00,01:13:00,1,20150331
3291,010415_00006,20150401,60,Nahariyya - Ben Gurion Airport,Nahariyya,1600,Nahariyya,04:46:00,04:46:00,11,20150331
4735,010415_00007,20150401,60,Nahariyya - Ben Gurion Airport,Ben Gurion Airport,1600,Nahariyya,02:13:00,02:13:00,1,20150331
4914,010415_00008,20150401,60,Nahariyya - Ben Gurion Airport,Nahariyya,1600,Nahariyya,05:48:00,05:48:00,12,20150331
4927,010415_00009,20150401,60,Nahariyya - Ben Gurion Airport,Ben Gurion Airport,1600,Nahariyya,03:13:00,03:13:00,1,20150331